### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by krainboltgreene** [sammi/bootstrap-jss#10]
Hi, I was wondering if this project plans to support v5. I would like to help.

**Comment by sammi** [comment]
It would be nice to support v5, I can add you as the contributor if you have time to do it.

**Comment by krainboltgreene** [comment]
Allow me to do the work first. How did you start with your current iteration? I wrote a css -> cssinjs converter and it turns out css is quite complex. I could theoretically "take what I get" and then hand mold it, but I'm hoping you have the keys to success.

**Comment by sammi** [comment]
Sure, my workflow is not focus on css itself, but works on a react component, using the library to generate css, and verify the component.

It seems up(component)-to-down(css), rather than down-to-up way.  Please feel free to make any changes you like.

**Comment by krainboltgreene** [comment]
Sorry, to clarify I wanted to know how you generated the javascript files containing the css definitions. Was it by hand or automatic?

**Comment by sammi** [comment]
I've done it manaully.
