### ISSUE TITLE
Package doesn't ship with javascript files

### ISSUE THREAD

**Issue by krainboltgreene** [sammi/bootstrap-jss#12]
![Screen Shot 2020-12-13 at 5 39 57 PM](https://user-images.githubusercontent.com/334809/102031263-45b13080-3d6a-11eb-8f1a-124ccbcc82fb.png)

**Comment by sammi** [comment]
Thanks for find this issue!
I've fixed it and update the README.md as well,
It's caused by missing ```yarn build``` before ```npm pack```.
