### ISSUE TITLE
CSS-in-JS generator?  How do you source the originals?

### ISSUE THREAD

**Issue by averyfreeman** [sammi/bootstrap-jss#23]
Hi,

Want to make sure I understand the purpose of your codebase correctly, it's a CSS-in-JS generator using bootstrap as a source, correct?

I've grepped your source code fairly extensively and I don't see any .css or .scss files, or links to bootstrap sources in any of your code.  How does your package source bootstrap? 

Am I misunderstanding the purpose of your repo?

Thanks
Avery

**Comment by sammi** [comment]
Hi Avery,
    It is not a generator, it is just rewrite bootstrap css by using jss.
     It’s purpose is building a bootstrap jss library, so we can manage css
by JavaScript.

Thanks,
Sammi

**Comment by averyfreeman** [comment]
Cool, thanks for the clarification.  

I'm looking at sassj3ss for v5 conversion, since your repo wasn't what I was looking for.  

How do you load the additional javascript library (e.g. `bootstrap.bundle.min.js`)
